site_name: Firefly III documentation
site_description: Documentation for Firefly III
site_author: James Cole
copyright: "&copy; <a href=\"mailto:james@firefly-iii.org\">James Cole</a>, licensed under <a href=\"https://github.com/firefly-iii/docs/blob/main/license\">Attribution-ShareAlike 4.0 International</a>."
repo_url: https://github.com/firefly-iii/firefly-iii/
edit_uri: https://github.com/firefly-iii/docs/tree/main/docs/docs
site_url: https://docs.firefly-iii.org/
dev_addr: '10.0.0.15:8000'
plugins:
  - search
  - 'git-revision-date'
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true

markdown_extensions:
  - admonition

nav:
  - Home: 'index.md'
  - 'Firefly III':
      - Home: firefly-iii/index.md
      - About Firefly III:
          - Introduction and features: firefly-iii/about-firefly-iii/introduction.md
          - Screenshots: firefly-iii/about-firefly-iii/screenshots.md
          - Demo website: firefly-iii/about-firefly-iii/demo.md
      - Installation:
          - Docker: firefly-iii/installation/docker.md
          - Kubernetes: firefly-iii/installation/kubernetes.md
          - Self-hosted server: firefly-iii/installation/self-hosted.md
          - Platforms: firefly-iii/installation/self-managed.md
          - Hosted by 3rd parties: firefly-iii/installation/third-parties.md
          - Upgrade instructions: firefly-iii/installation/upgrade.md
      - Advanced installation:
          - Configure email: firefly-iii/advanced-installation/email.md
          - Authentication: firefly-iii/advanced-installation/authentication.md
          - Backup: firefly-iii/advanced-installation/backup.md
          - Locales: firefly-iii/advanced-installation/locales.md
          - Cron jobs: firefly-iii/advanced-installation/cron.md
      - Features:
          - Command line usage: firefly-iii/features/commandline.md
          - Rules: firefly-iii/features/rules.md
          - Search: firefly-iii/features/search.md
          - Webhooks: firefly-iii/features/webhooks.md
          - Reports: firefly-iii/features/reports.md
      - Financial concepts:
          - Transactions: firefly-iii/financial-concepts/transactions.md
          - Organizing transactions: firefly-iii/financial-concepts/organizing.md
          - Tracking cash: firefly-iii/financial-concepts/tracking_cash.md
          - Accounts: firefly-iii/financial-concepts/accounts.md
          - Currencies: firefly-iii/financial-concepts/currencies.md
          - Piggy banks: firefly-iii/financial-concepts/piggies.md
          - Bills: firefly-iii/financial-concepts/bills.md
          - Recurring transactions: firefly-iii/financial-concepts/recurring.md
          - Reconciling accounts: firefly-iii/financial-concepts/reconcile.md
      - Importing data: firefly-iii/importing-data/index.md
      - Exporting data: firefly-iii/exporting-data/index.md
      - API:
          - API: firefly-iii/api/index.md
          - Special endpoints: firefly-iii/api/specials.md
      - More info:
          - Logo and name: firefly-iii/more-information/logo.md
          - License: firefly-iii/more-information/license.md
          - Architecture: firefly-iii/more-information/architecture.md
          - Security: firefly-iii/more-information/security.md
          - Missing features: firefly-iii/more-information/what-its-not.md
          - Personal finances: firefly-iii/more-information/personal-finances.md
          - Zero based budgeting: firefly-iii/more-information/zero-based-budgeting.md
          - Third-party tools: firefly-iii/more-information/3rdparty.md
      - FAQ:
          - General questions: firefly-iii/faq/general.md
          - Managing your finances: firefly-iii/faq/financials.md
          - Using Docker: firefly-iii/faq/docker.md
          - Installing and upgrading: firefly-iii/faq/installation.md
          - Self-hosting: firefly-iii/faq/self-hosted.md
          - Translating Firefly III: firefly-iii/faq/translate.md
          - Other questions: firefly-iii/faq/other.md
      - Support: firefly-iii/support/index.md
  - Data importer:
      - Home: data-importer/index.md
      - Installation:
          - Installation: data-importer/installation/index.md
          - Docker: data-importer/installation/docker.md
          - Self-hosted: data-importer/installation/self-hosted.md
          - Public installation: data-importer/installation/public.md
          - Configuration: data-importer/installation/configuration.md
          - Upgrading: data-importer/installation/upgrade.md
      - How to use:
          - How to use: data-importer/how-to-use/index.md
          - Select data source: data-importer/how-to-use/select-data-source.md
          - Configure import: data-importer/how-to-use/configure-import.md
          - Fine-tune CSV: data-importer/how-to-use/fine-tune-import.md
          - Map data: data-importer/how-to-use/map.md
          - Start the import: data-importer/how-to-use/start.md
          - Clean-up data: data-importer/how-to-use/clean-up-data.md
      - Advanced:
          - Advanced: data-importer/advanced/index.md
          - Auto-import: data-importer/advanced/automation.md
          - JSON: data-importer/advanced/json.md
          - Notifications: data-importer/advanced/notifications.md
          - Import transfers: data-importer/advanced/transfers.md
      - FAQ:
          - FAQ: data-importer/faq/index.md
          - Installation errors: data-importer/faq/installation-errors.md
          - Connection errors: data-importer/faq/connection-errors.md
          - Nordigen and Spectre: data-importer/faq/spectre-and-nordigen.md
          - Where to start?: data-importer/faq/where-to-start.md
          - Messy transactions: data-importer/faq/messy-transactions.md
          - Duplicates: data-importer/faq/duplicates.md
          - Re-import transactions: data-importer/faq/re-import.md
          - JSON file: data-importer/faq/json.md
      - More information:
          - Separate tool: data-importer/more-information/separate-tool.md
      - Support:
          - Support: data-importer/support/index.md
          - Issues: data-importer/support/issues.md
          - Roadmap: data-importer/support/roadmap.md
          - Contact: data-importer/support/contact.md
  - Other tools: other-tools/index.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  palette:
    scheme: fireflyiii
  logo: img/logo.png
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@ff3
    - icon: fontawesome/brands/github
      link: https://github.com/firefly-iii
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/firefly-iii/firefly-iii
    - icon: fontawesome/solid/globe
      link: https://www.firefly-iii.org/?mtm_campaign=documentation&mtm_kwd=bottom-link
