site_name: Firefly III documentation
site_description: Documentation for Firefly III
site_author: James Cole
copyright: "&copy; <a href=\"mailto:james@firefly-iii.org\">James Cole</a>, licensed under <a href=\"https://github.com/firefly-iii/docs/blob/main/license\">Attribution-ShareAlike 4.0 International</a>."
repo_url: https://github.com/firefly-iii/firefly-iii/
edit_uri: https://github.com/firefly-iii/docs/tree/main/docs/docs
site_url: https://docs.firefly-iii.org/
dev_addr: '10.0.0.15:8000'
plugins:
  - search
  - 'git-revision-date'
  - redirects:
      redirect_maps:
        'api/api.md': 'firefly-iii/api.md'
        'about-firefly-iii/demo.md': 'firefly-iii/about-firefly-iii/demo.md'
        'about-firefly-iii/grand-theory.md': 'firefly-iii/about-firefly-iii/personal-finances.md'
        'about-firefly-iii/features.md': 'firefly-iii/about-firefly-iii/introduction.md'
        'about-firefly-iii/introduction.md': 'firefly-iii/about-firefly-iii/introduction.md'
        'about-firefly-iii/personal-finances.md': 'firefly-iii/about-firefly-iii/personal-finances.md'
        'about-firefly-iii/screenshots.md': 'firefly-iii/about-firefly-iii/screenshots.md'
        'about-firefly-iii/security.md': 'firefly-iii/about-firefly-iii/security.md'
        'about-firefly-iii/what-its-not.md': 'firefly-iii/about-firefly-iii/what-its-not.md'
        'advanced-concepts/bills.md': 'firefly-iii/advanced-concepts/bills.md'
        'advanced-concepts/piggies.md': 'firefly-iii/advanced-concepts/piggies.md'
        'advanced-concepts/links.md': 'firefly-iii/advanced-concepts/links.md'
        'advanced-concepts/rules.md': 'firefly-iii/pages-and-features/rules.md'
        'advanced-concepts/recurring.md': 'firefly-iii/advanced-concepts/recurring.md'
        'advanced-concepts/reconcile.md': 'firefly-iii/advanced-concepts/reconcile.md'
        'advanced-concepts/reports.md': 'firefly-iii/advanced-concepts/reports.md'
        'advanced-installation.md': 'firefly-iii/index.md'
        'advanced-installation/analytics.md': 'firefly-iii/advanced-installation/analytics.md'
        'advanced-installation/authentication.md': 'firefly-iii/advanced-installation/authentication.md'
        'advanced-installation/backup.md': 'firefly-iii/advanced-installation/backup.md'
        'advanced-installation/cron.md': 'firefly-iii/advanced-installation/cron.md'
        'advanced-installation/email.md': 'firefly-iii/advanced-installation/email.md'
        'advanced-installation/locales.md': 'firefly-iii/advanced-installation/locales.md'
        'advanced-installation/upgrade.md': 'firefly-iii/installation/upgrade.md'
        'csv/upgrade/upgrade.md': 'csv/upgrade.md'
        'concepts/accounts.md': 'firefly-iii/concepts/accounts.md'
        'concepts/budgets.md': 'firefly-iii/concepts/budgets.md'
        'concepts/categories.md': 'firefly-iii/concepts/categories.md'
        'concepts/currencies.md': 'firefly-iii/concepts/currencies.md'
        'concepts/groups.md': 'firefly-iii/concepts/groups.md'
        'concepts/search.md': 'firefly-iii/pages-and-features/search.md'
        'concepts/tracking_cash.md': 'firefly-iii/concepts/tracking_cash.md'
        'concepts/tags.md': 'firefly-iii/concepts/tags.md'
        'concepts/transactions.md': 'firefly-iii/concepts/transactions.md'
        'contact/contact.md': 'firefly-iii/other-pages/contact.md'
        'errors-and-trouble-shooting/duplicate_transactions.md': 'csv/errors/duplicate_transactions.md'
        'errors-and-trouble-shooting/token_errors.md': 'csv/errors/token_errors.md'
        'exporting-data/export.md': 'firefly-iii/exporting-data.md'
        'faq/other.md': 'firefly-iii/faq/other.md'
        'faq/importing.md': 'firefly-iii/faq/importing.md'
        'faq/docker.md': 'firefly-iii/faq/docker.md'
        'faq/installation.md': 'firefly-iii/faq/installation.md'
        'faq/financials.md': 'firefly-iii/faq/financials.md'
        'faq/self_hosted.md': 'firefly-iii/faq/self_hosted.md'
        'faq/translate.md': 'firefly-iii/faq/translate.md'
        'firefly-iii/advanced-concepts/rules.md': 'firefly-iii/pages-and-features/rules.md'
        'firefly-iii/advanced-concepts/commandline.md': 'firefly-iii/pages-and-features/commandline.md'
        'firefly-iii/advanced-installation/upgrade.md': 'firefly-iii/installation/upgrade.md'
        'firefly-iii/concepts/search.md': 'firefly-iii/pages-and-features/search.md'
        'firefly-iii/exporting-data/export.md': 'firefly-iii/exporting-data.md'
        'help/json.md': 'csv/help/json.md'
        'installation/docker.md': 'firefly-iii/installation/docker.md'
        'installation/k8n.md': 'firefly-iii/installation/k8n.md'
        'installation/self_hosted.md': 'firefly-iii/installation/self_hosted.md'
        'installation/third_parties.md': 'firefly-iii/installation/third_parties.md'
        'installing-and-running/docker.md': 'csv/install/docker.md'
        'importing-data/faq.md': 'firefly-iii/importing-data/faq.md'
        'importing-data/spectre.md': 'firefly-iii/importing-data/introduction.md'
        'importing-data/others.md': 'firefly-iii/importing-data/introduction.md'
        'importing-data/introduction.md': 'firefly-iii/importing-data/introduction.md'
        'importing-data/upload.md': 'csv/usage/upload.md'
        'importing-data/roles.md': 'csv/usage/roles.md'
        'importing-data/command_line.md': 'csv/usage/command_line.md'
        'importing-data/map.md': 'csv/usage/map.md'
        'other-pages/3rdparty.md': 'firefly-iii/other-pages/3rdparty.md'
        'other-pages/contributing.md': 'firefly-iii/other-pages/contributing.md'
        'support/contribute.md': 'firefly-iii/support/contribute.md'
        'support/error_codes.md': 'firefly-iii/support/error_codes.md'
        'support/faq.md': 'firefly-iii/support/faq.md'
        'support/features.md': 'firefly-iii/support/features.md'
        'support/telemetry.md': 'firefly-iii/support/telemetry.md'
        'support/transaction_types.md': 'firefly-iii/support/transaction_types.md'
        'usage/map.md': 'csv/usage/map.md'
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true

markdown_extensions:
    - admonition

#    - def_list
#    - mdx_gh_links:
#        user: mkdocs
#        repo: mkdocs

nav:
  - Home: 'index.md'
  - 'Firefly III':
    - Introduction: firefly-iii/index.md
    - About Firefly III:
      - Introduction and features: firefly-iii/about-firefly-iii/introduction.md
      - Missing features: firefly-iii/about-firefly-iii/what-its-not.md
      - Screenshots : firefly-iii/about-firefly-iii/screenshots.md
      - Personal finances: firefly-iii/about-firefly-iii/personal-finances.md
      - Demo website: firefly-iii/about-firefly-iii/demo.md
      - Architecture: firefly-iii/about-firefly-iii/architecture.md
      - Security: firefly-iii/about-firefly-iii/security.md
      - Logo and name: firefly-iii/about-firefly-iii/logo.md
    - Installation:
      - Docker: firefly-iii/installation/docker.md
      - Kubernetes: firefly-iii/installation/k8n.md
      - Self-hosted server: firefly-iii/installation/self_hosted.md
      - Hosted by 3rd parties: firefly-iii/installation/third_parties.md
      - Upgrade instructions: firefly-iii/installation/upgrade.md
    - Support:
      - Feature requests and roadmap: firefly-iii/support/features.md
      - Reporting bugs: firefly-iii/support/bugs.md
      - Contribute to Firefly III: firefly-iii/support/contribute.md
      - FAQ: firefly-iii/support/faq.md
      - Transaction types: firefly-iii/support/transaction_types.md
      - Telemetry: firefly-iii/support/telemetry.md
      - Error codes: firefly-iii/support/error_codes.md
    - Pages and features:
      - Administration: firefly-iii/pages-and-features/admin.md
      - Command line usage: firefly-iii/pages-and-features/commandline.md
      - Rules: firefly-iii/pages-and-features/rules.md
      - Search: firefly-iii/pages-and-features/search.md
      - Webhooks: firefly-iii/pages-and-features/webhooks.md
    - FAQ:
      - General questions: firefly-iii/faq/general.md
      - Managing your finances: firefly-iii/faq/financials.md
      - Using Docker: firefly-iii/faq/docker.md
      - Installing and upgrading: firefly-iii/faq/installation.md
      - Self-hosting: firefly-iii/faq/self_hosted.md
      - Importing data: firefly-iii/faq/importing.md
      - Translating Firefly III: firefly-iii/faq/translate.md
      - Other questions: firefly-iii/faq/other.md
    - Concepts:
      - Transactions: firefly-iii/concepts/transactions.md
      - Accounts: firefly-iii/concepts/accounts.md
      - Budgets: firefly-iii/concepts/budgets.md
      - Categories: firefly-iii/concepts/categories.md
      - Tags: firefly-iii/concepts/tags.md
      - Currencies: firefly-iii/concepts/currencies.md
      - Groups: firefly-iii/concepts/groups.md
      - Tracking cash: firefly-iii/concepts/tracking_cash.md
    - Advanced installation:
      - Configure email: firefly-iii/advanced-installation/email.md
      - Authentication: firefly-iii/advanced-installation/authentication.md
      - Analytics: firefly-iii/advanced-installation/analytics.md
      - Backup: firefly-iii/advanced-installation/backup.md
      - Locales: firefly-iii/advanced-installation/locales.md
      - Cron jobs: firefly-iii/advanced-installation/cron.md
    - Importing data:
      - Introduction: firefly-iii/importing-data/introduction.md
      - FAQ: firefly-iii/importing-data/faq.md
    - Exporting data: firefly-iii/exporting-data.md
    - Advanced concepts:
      - Piggy banks: firefly-iii/advanced-concepts/piggies.md
      - Bills: firefly-iii/advanced-concepts/bills.md
      - Recurring transactions: firefly-iii/advanced-concepts/recurring.md
      - Reports: firefly-iii/advanced-concepts/reports.md
      - Links: firefly-iii/advanced-concepts/links.md
      - Reconciling accounts: firefly-iii/advanced-concepts/reconcile.md
    - API:
      - API: firefly-iii/api.md
    - Other pages:
      - Contact and credits: firefly-iii/other-pages/contact.md
      - Third-party tools: firefly-iii/other-pages/3rdparty.md
      - Contributing: firefly-iii/other-pages/contributing.md
  - CSV importer:
    - Introduction: csv/index.md
    - Installing and running:
      - Configuration: csv/install/configure.md
      - Docker: csv/install/docker.md
      - Self-hosted: csv/install/self_hosted.md
      - Upgrading: csv/upgrade.md
      - Public installation: csv/help/public.md
    - Help:
      - The JSON file: csv/help/json.md
      - Pre-made configuration: csv/help/config.md
      - Public installation: csv/help/public.md
    - Importing data:
      - Uploading files: csv/usage/upload.md
      - Configuring your import: csv/usage/configure.md
      - Setting roles for columns: csv/usage/roles.md
      - Mapping data: csv/usage/map.md
      - Importing over command line: csv/usage/command_line.md
      - Importing using POST: csv/usage/post.md
      - Emailing results: csv/usage/email.md
      - Importing transfers: csv/usage/importing_transfers.md
    - Errors and trouble shooting:
      - Duplicate transactions: csv/errors/duplicate_transactions.md
      - Personal Access Token errors: csv/errors/token_errors.md
      - Frequently seen issues: csv/errors/freq_errors.md
      - Frequently asked questions: csv/errors/freq_questions.md
      - Bad CSV files: csv/errors/bad_files.md
  - Other data importers:
    - Introduction: other-data-importers/index.md
    - Installing and running:
      - Docker: other-data-importers/install/docker.md
      - Self-hosted: other-data-importers/install/self_hosted.md
      - Configuration: other-data-importers/install/configure.md
    - Upgrading: other-data-importers/upgrade.md
    - Importing data:
      - Uploading config: other-data-importers/usage/upload.md
      - Filter the import: other-data-importers/usage/filter_import.md
      - Configuring your import: other-data-importers/usage/configure.md
      - Mapping data: other-data-importers/usage/map.md
      - Importing over command line: other-data-importers/usage/command_line.md
      - JSON file: other-data-importers/usage/json.md
    - Errors and trouble shooting:
      - Token errors: other-data-importers/errors/token_errors.md
      - Frequently seen issues: other-data-importers/errors/freq_errors.md
      - Frequently asked questions: other-data-importers/errors/freq_questions.md
  - Other tools:
    - Introduction: other-tools/index.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  palette:
    scheme: fireflyiii
  logo: img/logo.png
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Firefly_III
    - icon: fontawesome/brands/github
      link: https://github.com/firefly-iii
    - icon: fontawesome/brands/reddit
      link: https://old.reddit.com/r/FireflyIII
