name: Publish documentation
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt install -y python3-pip python3-setuptools python3-dev python3-venv python3-wheel
          sudo rm /usr/bin/python
          sudo rm /usr/bin/pip
          sudo ln -s /usr/bin/python3 /usr/bin/python
          sudo ln -s /usr/bin/pip3 /usr/bin/pip
          python --version
          pip --version
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-plugin mkdocs-redirects mkdocs-minify-plugin

      - name: Build documentation
        run: |
          cd $GITHUB_WORKSPACE/docs
          python -m mkdocs build --clean
      - name: Upload to Azure Blob Storage
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.connectionString }}
        run: |
          cd $GITHUB_WORKSPACE/docs
          az storage blob upload-batch \
                            -s ./site \
                            --dryrun \
                            --no-progress
