name: Publish documentation
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE/docs
          ls
          sudo apt install -y python3-pip
          sudo ln -s /usr/bin/python3 /usr/bin/python
          sudo ln -s /usr/bin/pip3 /usr/bin/pip
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-plugin mkdocs-redirects mkdocs-minify-plugin
          python --version
          mkdocs --build

