name: Publish documentation
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt install -y python3-pip python3-setuptools python3-dev python3-venv python3-wheel libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          sudo rm /usr/bin/python
          sudo rm /usr/bin/pip
          sudo ln -s /usr/bin/python3 /usr/bin/python
          sudo ln -s /usr/bin/pip3 /usr/bin/pip
          pip install mkdocs 
          pip install git+https://${MKDOCS_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git@master
          pip install mkdocs-git-revision-date-plugin mkdocs-redirects mkdocs-minify-plugin pillow cairosvg
        env:
          MKDOCS_TOKEN: ${{ secrets.MKDOCS_TOKEN }}
      - name: Build documentation
        run: |
          cd $GITHUB_WORKSPACE/docs
          grep -rl '%PHPVERSION' ./ | xargs sed -i 's/%PHPVERSION/8\.2/g'
          grep -rl '%IMPORTERVERSION' ./ | xargs sed -i 's/%IMPORTERVERSION/1\.3\.9/g'
          grep -rl '%FFVERSION' ./ | xargs sed -i 's/%FFVERSION/6\.0\.30/g'
          python -m mkdocs build --clean

          # also copy security.txt
          cp -r docs/.well-known site/.well-known
      - name: Upload to Azure Blob Storage
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.connectionString }}
        run: |
          cd $GITHUB_WORKSPACE/docs
          az storage blob upload-batch \
                            -s ./site \
                            -d 'https://fireflyiiidocs.blob.core.windows.net/$web' \
                            --overwrite
